CREATE TABLE TBL_PRODUCT(
	productNum NUMBER(30) PRIMARY KEY,
	productName VARCHAR2(2000) UNIQUE,
	productPrice NUMBER(30) NOT NULL,
	productStock NUMBER(30) NOT NULL,
	productCategories VARCHAR2(2000) NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT;

SELECT *FROM TBL_PRODUCT;


INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '단감명작', 39000, 1000, '과실주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, 'Golden Peach', 43500, 2000, '과실주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, 'SWEET MAMA', 19800, 4500, '과실주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '마쓰이 쿠라요시 퓨어몰트 래빗 레이블', 140000, 4500, '위스키');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '벤로막10년', 99800, 1250, '위스키');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '에반 윌리엄스 블랙', 210000, 500, '위스키');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '하이랜드 파크 18년 700mL', 128000, 2100, '위스키');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '연꽃 담은 술 8도 850ml', 12000, 5000, '막걸리');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '이천미 예술 누룩막걸리 14도 750ml', 4000, 2100, '막걸리');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '이화백주 940ml', 14000, 15000, '막걸리');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '지란지교 프리미엄 약주 15도 375ml', 12000, 2100, '막걸리');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '오미나라 전통주 고운달 도자기숙성 52도 500ml', 360000, 100, '브랜디');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '애플리즈 금과명주세트 40도 750ml', 49000, 1000, '브랜디');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, 'KY올드 마르퀴스XO세트', 120000, 500, '브랜디');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '식품명인 문배주양조원 명작 1000 40%', 125000, 500, '소주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '양반안동소주 23년산 로얄안동소주 45도 800ml', 145000, 500, '소주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '양반안동소주 24년산 로얄 45도 600ml', 108000, 500, '소주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '제주샘주 고소리술 도자기 40도 500ml', 80000, 800, '소주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '궁중술 왕주 700ml 40도 민속주왕주', 35000, 1000, '청주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '양촌양조 양촌 우렁이쌀 청주 14도 500ml', 16000, 1200, '청주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '엄청주 360ml', 10000, 2000, '청주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '우포의 아침 조선 주조사 14도 300ml', 4000, 5000, '청주');

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES)
VALUES(SEQ_PRODUCT.nextval, '초가 한청 15도 700ml', 20000, 1000, '청주');
