CREATE TABLE TBL_PRODUCT(
	productNum NUMBER(30) PRIMARY KEY,
	productName VARCHAR2(2000) UNIQUE,
	productPrice NUMBER(30) NOT NULL,
	productStock NUMBER(30) NOT NULL,
	productCategories VARCHAR2(2000) NOT NULL,
	productUpdate VARCHAR2(5) DEFAULT 'N'
);

INSERT INTO TBL_PRODUCT
(PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTOCK, PRODUCTCATEGORIES, PRODUCTUPDATE)
VALUES(SEQ_PRODUCT.NEXTVAL, 'dmdka', 1000, 10, '증류주', 'N');

CREATE SEQUENCE SEQ_PRODUCT;

DROP TABLE TBL_PRODUCT;
DROP TABLE TBL_FILE;
DROP TABLE Tbl_cart;
DROP SEQUENCE SEQ_PRODUCT;

CREATE TABLE TBL_FILE(
	fileName VARCHAR2(2000) PRIMARY KEY,		-- 중복이 되면 카운팅이 되는 파일 이름
	productNum NUMBER(30),
	fileNameOriginal VARCHAR2(2000),	-- 파일 이름
	CONSTRAINT FK_FILES_PRODUCT FOREIGN KEY(productNum)
	REFERENCES TBL_PRODUCT(productNum) ON DELETE CASCADE
);

UPDATE TBL_PRODUCT
		SET PRODUCTPRICE=1,
		PRODUCTSTOCK=1
		WHERE PRODUCTNUM=1;

SELECT * FROM TBL_PRODUCT;
SELECT * FROM TBL_FILE;
SELECT * FROM TBL_PAYMENT;

CREATE TABLE TBL_PAYMENT(
   id varchar2(20) NOT NULL,
   productNum NUMBER(30) NOT NULL,
   productName VARCHAR2(2000) NOT NULL,
   productPrice NUMBER(30) NOT NULL,
   productCategories VARCHAR2(2000) NOT NULL,
   fileName VARCHAR2(2000) NOT NULL,
   amount number(10) NOT NULL,
   zipcode VARCHAR2(2000) NOT NULL,
   address VARCHAR2(2000) NOT NULL,
   addressDetail VARCHAR2(2000) NOT NULL,
   addressEtc VARCHAR2(2000) NOT NULL
);

INSERT INTO TBL_PAYMENT
		(ID, PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTCATEGORIES, FILENAME, AMOUNT, ZIPCODE, ADDRESS, ADDRESSDETAIL, ADDRESSETC)
		VALUES('dmdka', 1, 'dmdka', 1, 'dmdka', 
		'dmdka', 1, 'dmdka', 'dmdka', 'dmdka', 'dmdka');
		
CREATE TABLE Tbl_cart(
	cartNum number(10) PRIMARY KEY,
	id varchar2(20) NOT NULL,
	productNum NUMBER(30) NOT NULL,
	productName VARCHAR2(2000) NOT NULL,
	productPrice NUMBER(30) NOT NULL,
	productCategories VARCHAR2(2000) NOT NULL,
	fileName VARCHAR2(2000) NOT NULL,
	amount number(10) NOT null
);
 DROP TABLE tbl_cart;
 
CREATE SEQUENCE SEQ_cart;
SEQ_CART.nextval



SELECT *FROM TBL_CART tc ;

SELECT *FROM TBL_CART tc WHERE id = '${value}';

UPDATE TBL_CART
SET ID='', PRODUCTNUM=0, PRODUCTNAME='', PRODUCTPRICE=0, PRODUCTCATEGORIES='', FILENAME='', AMOUNT=0;

INSERT INTO TBL_CART
(CARTNUM, ID, PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTCATEGORIES, FILENAME, AMOUNT)
VALUES(1, 'dmdka', 1, 'dmdka', 100, 'dmdka', 'ex01.png', 10);
INSERT INTO TBL_CART
(CARTNUM, ID, PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTCATEGORIES, FILENAME, AMOUNT)
VALUES(2, 'dmdka1', 2, 'dmdka1', 1100, 'dmdka1', 'ex02.png', 110);
