-- PATMENT TABLE
CREATE TABLE TBL_PAYMENT
(
   idx NUMBER PRIMARY KEY,
   id varchar2(20) NOT NULL,
   productNum NUMBER(30) NOT NULL,
   productName VARCHAR2(2000) NOT NULL,
   productPrice NUMBER(30) NOT NULL,
   productCategories VARCHAR2(2000) NOT NULL,
   fileName VARCHAR2(2000) NOT NULL,
   amount number(10) NOT NULL,
   zipcode VARCHAR2(2000) NOT NULL,
   address VARCHAR2(2000) NOT NULL,
   addressDetail VARCHAR2(2000) NOT NULL,
   addressEtc VARCHAR2(2000) NOT NULL,
   pDate DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_PAYMENT;

-- PAYMENT TABLE 예시
INSERT INTO TBL_PAYMENT (idx, ID, PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTCATEGORIES, FILENAME, AMOUNT, ZIPCODE, ADDRESS, ADDRESSDETAIL, ADDRESSETC)
VALUES(SEQ_PAYMENT.nextval, 'HYC666', 1, '단감명작', 39000, '과실주', 'gam.png', 2, '666-666', '66666 경기 서울시 사당구', '사당로 66번지', '없음');

INSERT INTO TBL_PAYMENT (idx, ID, PRODUCTNUM, PRODUCTNAME, PRODUCTPRICE, PRODUCTCATEGORIES, FILENAME, AMOUNT, ZIPCODE, ADDRESS, ADDRESSDETAIL, ADDRESSETC)
VALUES(SEQ_PAYMENT.nextval, 'HYC666', 10, '지란지교 프리미엄 약주 15도 375ml', 12000, '막걸리', '지란지교 프리미엄 약주 15도 375ml25.png', 2, '666-666', '66666 경기 서울시 사당구', '사당로 66번지', '없음');

