--추천상품 테이블
CREATE TABLE Recommend(
fileName VARCHAR2(2000),
productPrice NUMBER(30),
productName VARCHAR2(2000),
productNum NUMBER(30)
);

DROP TABLE RECOMMEND ;

SELECT * FROM recommend;

--추천상품 조회
SELECT * FROM recommend
order by PRODUCTNAME;

--추천상품 삭제
DELETE FROM recommend
WHERE PRODUCTNAME = ?;

--추천상품 등록
INSERT INTO RECOMMEND (FILENAME, PRODUCTPRICE, PRODUCTNAME)VALUES(?,?,?,?);


INSERT INTO RECOMMEND (FILENAME, PRODUCTPRICE, PRODUCTNAME,productNum)VALUES('gam.png',39000,'단감명작',1);
INSERT INTO RECOMMEND (FILENAME, PRODUCTPRICE, PRODUCTNAME,productNum)VALUES('goldenpeach.png',43500,'Golden Peach',2);
INSERT INTO RECOMMEND (FILENAME, PRODUCTPRICE, PRODUCTNAME,productNum)VALUES('sweetMAMA.png',19800,'SWEET MAMA',3);
INSERT INTO RECOMMEND (FILENAME, PRODUCTPRICE, PRODUCTNAME,productNum)VALUES('mazue.png',140000,'마쓰이 쿠라요시 퓨어몰트 래빗 레이블',4);
INSERT INTO RECOMMEND (FILENAME, PRODUCTPRICE, PRODUCTNAME,productNum)VALUES('벤로막 10년.png',99800,'벤로막10년',5);

